name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    - name: freetype
      run: sudo apt-get update && sudo apt-get install -y libfreetype6-dev fonts-noto
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
